#!/bin/bash

function UPDATE {
if [[ ! -d ~/.milux ]];then
	mkdir ~/.milux
fi
if [[ ! -f ~/.milux/vcv ]];then
	echo "v-2.0" > ~/.milux/vcv
fi

echo -e "$G"
logo
echo -e "$G Buscando la version mas nueva.."
sleep 2
echo -e "Espera por favor"
curl https://raw.githubusercontent.com/miluxmil/milux/master/NV > /dev/null 2>&1 > tmpv
mv tmpv  ~/.milux/
CV=$(cat ~/.milux/vcv)
NV=$(cat ~/.milux/tmpv)
if [ "$CV" = "$NV" ];then
	clear
	rm ~/.milux/tmpv
	logo
	echo -e "$Y Tu script esta Actualizado! tu version es:$RE $CV"
	sleep 2
else
	CV=$(cat ~/.milux/vcv)
	echo -e $Y"==============================="
	 echo -e $Y"=                             ="
	 echo -e $Y"=  Nueva Actualizacion! $NV  ="
	 echo -e $Y"=                             ="
	 echo -e $Y"=$G  Version actual: $CV $Y     ="
	 echo -e $Y"=                             ="
	 echo -e $Y"==============================="
	 echo -e "$Y Quieres actualizar?$RE"
	 read -p "
	 y/n >> " SN
	 case $SN in
	 	 y)
		 rm ~/.milux/vcv
		 echo "$NV" > ~/.milux/vcv
		 curl https://raw.githubusercontent.com/miluxmil/milux/master/updater > /dev/null 2>&1 > TMP
		 chmod 777 TMP
		 bash TMP;rm TMP
		 echo -e $G"Instalado Correctamente!"
		 sleep 2
;;
		 n)

		 rm ~/.milux/tmpv
		 bash termux-url-opener $1
		 ;;
 esac
fi
}

