#!/data/data/com.termux/files/usr/bin/bash
# Copyright 2018 ::milux::

C='\033[1;36m'
G='\033[1;32m'
R='\033[1;31m'
Y='\033[1;33m'
B='\033[1;34m'
P='\033[1;35m'
RE='\033[0m'

echo -e $R"############################"
echo -e $R"#                          #"
echo -e $R"#  $G Copyright 2018 milux  $R #"
echo -e $R"#                          #"
echo -e $R"############################"
echo -e $RE"Escribe una opcion.
"

echo -e $G"[$RE 1$G ]$Y Solo audio"
echo -e $G"[$RE 2$G ]$Y Video calidad 360p"
echo -e $G"[$RE 3$G ]$Y Video calidad 480p"
echo -e $G"[$RE 4$G ]$Y Video calidad 720p"
echo -e $G"[$RE 5$G ]$Y Video calidad 1080p
"
setterm -foreground white 
command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s -f'
read -p ">> " option
echo
echo -e $G"Descargando..$RE"

if [ "$option" -eq "1" ]
then
    echo "$command 140" > ~/.config/youtube-dl/config
    youtube-dl $1
    function converter {
    echo -e $G"Quieres convertirlo a mp3? s/n
   $RE"
    read -p ">> " sino
    	
	if [ "$sino" = "s" ];then
		ls /sdcard/youtube | cat -n
		echo -e $G"selecciona tu archivo a convertir
		$RE"
		read -p ">> " option
		ls /sdcard/youtube > filelist
		file=$(head -n $option filelist | tail -n+$option filelist )
		echo "$file" > tmp | sed -i "2,100d" tmp
		namesong=$(cat tmp)
		echo -e "$G"
		name=$(basename /sdcard/youtube/"$namesong" .m4a)

		ffmpeg -i /sdcard/youtube/"$namesong" -c:a libmp3lame /sdcard/youtube/"$name.mp3"
		rm filelist tmp /sdcard/youtube/"$namesong"
		echo -e "$RE"
		echo -e $C"listo.. Hasta luego!!$RE"
		sleep 2
	elif [ -z $sino ];then
		echo -e $R"Responde con s o n"
		sleep 2
		converter

	else
		echo -e $G"bye bye.. $RE"
		sleep 2
	fi
}

converter

elif [ "$option" -eq "2" ]
then
    echo "$command \"best[height<=360]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "3" ]
then
    echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "4" ]
then
    echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "5" ]
then
    echo "$command \"best[height<=1080]\"" > ~/.config/youtube-dl/config
    youtube-dl $1
fi
