#!/bin/bash
if [[ ! -d ~/.milux ]];then
mkdir ~/.milux
fi

cd ~/.milux

curl https://raw.githubusercontent.com/miluxmil/milux/master/termux-url-opener > /dev/null 2>&1 > termux-url-opener;VAR1=$? 
if [ $VAR1 = 0 ];then
	echo "Downloader..  OK "
	sleep 1
	chmod 777 termux-url-opener
	mv termux-url-opener ~/bin/
else 
	echo "ocurrió un problema"
	sleep 3
	exit 1
fi

curl https://raw.githubusercontent.com/miluxmil/milux/master/update > /dev/null 2>&1 > update;VAR2=$?

if [ $VAR2 = 0 ];then
	echo "Update... OK"
	sleep 1
	mv update ~/bin/
else
	echo "ocurrió un problema"
	sleep 3
	exit
fi 

echo -e $G"
Lista de cambios$RE

*$G Optimizacion
* Se reparo problema de solo video
* Se resolvieron algunos errores al detectar formatos
* Cambio de cursor
* Mejoras
* Optimizaciones
* Se reparo descargas Spotify
* Optimizacion
* Se agregó opción salir
* chequeo en todos los modos
* Modo de espera cambiado
* Algunas mejoras
19/jun/20
* Mejoras esteticas
* Errores menores
26/jun/2020
* Comprobación más completa
* Errores menores"
read -n 1 -p "
ENTER para salir"



