#!/data/data/com.termux/files/usr/bin/bash

wget https://raw.githubusercontent.com/miluxmil/milux/master/termux-url-opener > /dev/null 2>&1
wget https://raw.githubusercontent.com/miluxmil/milux/master/update > /dev/null 2>&1
chmod 777 termux-url-opener
mv termux-url-opener update ~/bin/
