#!/bin/bash                                                                                                                 wget https://raw.githubusercontent.com/miluxmil/milux/master/termux-url-opener -O ~/bin/termux-url-opener                                                                                 wget https://raw.githubusercontent.com/miluxmil/milux/master/update -O ~/bin/update
wget https://raw.githubusercontent.com/miluxmil/milux/master/termux-url-opener -O ~/bin/termux-url-opener

wget https://raw.githubusercontent.com/miluxmil/milux/master/update -O ~/bin/update

exit 1
